#!/usr/bin/env python
import sys, os

# ///////////////////////////////////////////////////////////////////////////
# ///    Useage: dir/*.root ->(merge)-> results_merged/samplename.root    ///
# ///         to apply for all folders in pwd at once, enter 'all',       ///
# ///      otherwise only specific dir name where root files are in       ///
# ///////////////////////////////////////////////////////////////////////////

#user_input = sys.argv[1]
"""
if "results_merged" not in os.listdir(os.getcwd()):
    os.system("mkdir results_merged")
    print "'results_merged' has been created."
"""

version="%s"%os.environ["CMSSW_VERSION"]
dirname = "test"
pstored="/xrootd/store/user/%s/nanoAOD/%s/"%(os.environ['USER'],dirname)
#pstored = "/cms/scratch/daniel/nanoAOD/src/nano/analysis/h2mu/Results/CSV/"

pmerged=pstored+"results_merged/" 

if pmerged not in os.listdir(pstored):
    os.system("mkdir -p "+pmerged)
    print "'results_merged' has been created."

#pwd = os.getcwd()+'/'
print pstored, pmerged, os.listdir(pstored)
dir_list = [x for x in os.listdir(pstored) if (os.path.isdir(pstored+x) and x != "results_merged")]
print dir_list

failed_list = []
for d in dir_list:
    print pstored+d
    root_list = [x for x in os.listdir(pstored+d) if (("nanoAOD" in x) and x.endswith(".root"))]
    file_names = ""
    for x in root_list:
        file_names += " %s/%s"%(pstored+d,x)
    if len(root_list) == 0:
        failed_list.append(d)
    else:
        #os.system("hadd -f %s.root %s"%(pmerged+"h2muAnalyzer_"+d,file_names))
        print "hadd -f %s.root %s"%(pmerged+"tth2mu_"+d,file_names)
        os.system("hadd -f %s.root %s"%(pmerged+"tth2mu_"+d,file_names))

if len(failed_list) > 0:
    print
    print " ** What failed:    ", failed_list
    print



