version: 2
jobs:
  build:
    docker:
      - image: watsonianj/cmssw:CMSSW_9_4_6_git4
    steps:
      - checkout
      - run:
          name: CMSSW
          command: pwd && ls && source /opt/cms/cmsset_default.sh && cd ~ && scram project CMSSW CMSSW_9_4_6 && cd CMSSW_9_4_6 && ln -s ~/project src/nano && scram b
